# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - aad-deployed-app(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: 425single
        app-settings-json: ${{ secrets.APP_SETTINGS }}
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_SINGLETENANT_WEBAPP }}
        package: ${{env.DOTNET_ROOT}}/myapp
    
    - name: Configure App Service settings
    - uses: azure/appservice-settings@v1
      with:
        app-name: 425single
        app-settings-json: ${{ secrets.AZURE_SINGLETENANT_SETTINGS }}
      id: settings
    - run: echo "The webapp-url is ${{ steps.settings.outputs.webapp-url }}"